matrix:
  include:
    - language: c
      compiler: gcc
      script: make
    - language: c
      compiler: clang
      script: make
    - name: ppc64el
      language: c
      script: make qemu arch ARCH=ppc64el
    - language: python
      python: "2.7"
      before_install: pip install cython
      script: python setup.py build_ext
    - language: python
      python: "3.5"
      before_install: pip install cython
      script: python setup.py build_ext
    - language: python
      python: "3.6"
      before_install: pip install cython
      script: python setup.py build_ext
